// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAce1KhewSFyx5FE8vX1X3FhxW5hzLR5SY',
    appId: '1:198196393156:web:535d51c69b48ad803d0591',
    messagingSenderId: '198196393156',
    projectId: 'threads-clone-e0e0d',
    authDomain: 'threads-clone-e0e0d.firebaseapp.com',
    storageBucket: 'threads-clone-e0e0d.appspot.com',
    measurementId: 'G-0W05YZ42K4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8DksRS99q1I4eiov5ZZdgDLWqOGQ4juM',
    appId: '1:198196393156:android:afb916f811fb854d3d0591',
    messagingSenderId: '198196393156',
    projectId: 'threads-clone-e0e0d',
    storageBucket: 'threads-clone-e0e0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlJfENc054pcZHBeuE_M4QZQcZRas4y4U',
    appId: '1:198196393156:ios:c35537bf02d96bff3d0591',
    messagingSenderId: '198196393156',
    projectId: 'threads-clone-e0e0d',
    storageBucket: 'threads-clone-e0e0d.appspot.com',
    iosBundleId: 'com.example.threadsClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlJfENc054pcZHBeuE_M4QZQcZRas4y4U',
    appId: '1:198196393156:ios:e5e8f0a7961dc1403d0591',
    messagingSenderId: '198196393156',
    projectId: 'threads-clone-e0e0d',
    storageBucket: 'threads-clone-e0e0d.appspot.com',
    iosBundleId: 'com.example.threadsClone.RunnerTests',
  );
}
